### ISSUE TITLE
[BUG] App doesn't asks for touch ID

### ISSUE THREAD

**Issue by bhrg3se** [seknox/fireser#134]
## Describe the bug:

App doesn't asks for touch ID after app restart.

## Steps to reproduce:

- Enable app authentication (touch ID)
- Kill the app
- Open the app

**Comment by sshahcodes** [comment]
This issue is related to CodePush and App freezes even if we do not enable touchID. 
If we ignore CodePush update after installation, this bug never appears. Please create a new Issue to track CodePush related issue.
