### ISSUE TITLE
[BUG] Scan result is not saved in AsyncStorage

### ISSUE THREAD

**Issue by bhrg3se** [seknox/fireser#137]
## Describe the bug:

After a successful scan, the scan results are not seen in "Protected Accounts" page.

## Log file / Code snippet / Screenshots:

![Screen Shot 2021-04-04 at 2 38 17 PM](https://user-images.githubusercontent.com/10883400/113503742-67ba0300-9553-11eb-8db3-f42a07e3cc72.png)

**Comment by sshahcodes** [comment]
FYI: this is only happening in production mode and when CodePush updates are installed
